#!/bin/bash
# Generates docs/synapse-bard/cli.md from what the binaries themselves print
# for --help. Adapted from docs/synapse/generate-cli-reference.sh -- same
# mechanism, `synapse-bard`/`synapse-bard-hook` in place of
# `synapse`/`synapse-hook`. See that file for the fuller "why generate at
# all" rationale; this header only notes what differs.
#
# Usage: docs/synapse-bard/generate-cli-reference.sh [--check]
#
#   --check  exit 1 if docs/synapse-bard/cli.md is out of date, without
#            writing it. Wired into the test suite, so a stale reference
#            fails visibly instead of quietly describing a command that has
#            moved on.
#
# EVERY --help MUST BE ENVIRONMENT-INDEPENDENT, checked here the same way the
# synapse generator checks it: each one runs under `env -i` from a directory
# outside any git repo.
#
# Exit codes: 0 ok (or up to date), 1 out of date with --check, or a --help
# that failed; 2 usage error
set -euo pipefail

readonly HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT="$(cd "$HERE/../.." && pwd)"
readonly OUT="$HERE/cli.md"
readonly BARD="${SYNAPSE_BARD_BIN:-$ROOT/zig-out/bin/synapse-bard}"
readonly BARD_HOOK="${SYNAPSE_BARD_HOOK_BIN:-$ROOT/zig-out/bin/synapse-bard-hook}"

usage() { # usage [exit-code]
  awk '/^# Usage:/ { p = 1 } p && !/^#/ { exit } p { sub(/^# ?/, ""); print }' "$0" >&2
  exit "${1:-2}"
}

CHECK=false
case "${1:-}" in
  "")        ;;
  --check)   CHECK=true ;;
  -h|--help) usage 0 ;;
  *)         usage ;;
esac

for bin in "$BARD" "$BARD_HOOK"; do
  [ -x "$bin" ] || {
    echo "generate-cli-reference: no binary at $bin -- run 'zig build', or set" >&2
    echo "  SYNAPSE_BARD_BIN/SYNAPSE_BARD_HOOK_BIN to point at ones already built" >&2
    exit 1
  }
done

# `env -i` from /tmp: no HOME, no PATH beyond the basics, and nowhere near a
# git repo. A --help that needs any of those is a bug in that subcommand.
help_for() { # help_for <binary> [subcommand...]
  local bin="$1"; shift
  (cd /tmp && env -i PATH=/usr/bin:/bin HOME=/nonexistent "$bin" "$@" --help 2>&1)
}

# CHECKED SEPARATELY FROM RENDERING -- see docs/synapse/generate-cli-reference.sh
# for why a `help_for` failure inside a command substitution can't be trusted
# to end the script on its own.
check_help() { # check_help <binary> [subcommand...]
  local bin="$1"
  if ! (cd /tmp && env -i PATH=/usr/bin:/bin HOME=/nonexistent "$@" --help >/dev/null 2>&1); then
    shift
    echo "generate-cli-reference: '$(basename "$bin") $* --help' exited non-zero" >&2
    echo "  every --help must answer without an environment; see this file's header" >&2
    exit 1
  fi
}

validate() {
  check_help "$BARD"
  check_help "$BARD_HOOK"
  local sub
  while read -r sub; do
    [ -n "$sub" ] || continue
    check_help "$BARD" "$sub"
  done < <(subcommands)
}

subcommands() {
  # The listing in `synapse-bard --help` is the authority on what exists, so
  # a subcommand added without a usage line is one this reference cannot
  # mention -- the right pressure, same as the synapse generator.
  help_for "$BARD" | sed -n 's/^  \([a-z][a-z-]*\) .*/\1/p' | awk '!seen[$0]++'
}

render() {
  cat <<'EOF'
# CLI reference

Generated by `docs/synapse-bard/generate-cli-reference.sh` from what the
binaries print for `--help`. Do not edit by hand; run the generator.

Two binaries, mirroring `synapse`/`synapse-hook`'s own relationship.
`synapse-bard` is the tooling a person or an agent runs; `synapse-bard-hook`
carries its Claude Code hooks and is registered in `settings.json` rather
than invoked directly. Unlike `synapse`, neither binary ever imports
`treesitter` -- `synapse-bard` parses YAML frontmatter only, so its whole
build links no libtree-sitter and needs no C compiler, not just the hook
side.

EOF

  # The `\n` before each closing fence is load-bearing -- see the synapse
  # generator's own comment on this same line for why.
  printf '## synapse-bard\n\n```\n%s\n```\n\n' "$(help_for "$BARD")"

  local sub
  while read -r sub; do
    [ -n "$sub" ] || continue
    printf '### synapse-bard %s\n\n```\n%s\n```\n\n' "$sub" "$(help_for "$BARD" "$sub")"
  done < <(subcommands)

  printf '## synapse-bard-hook\n\n```\n%s\n```\n' "$(help_for "$BARD_HOOK")"
}

validate

if [ "$CHECK" = true ]; then
  if [ ! -f "$OUT" ]; then
    echo "generate-cli-reference: $OUT does not exist -- run this script" >&2
    exit 1
  fi
  if diff -q <(render) "$OUT" >/dev/null; then
    echo "docs/synapse-bard/cli.md is up to date"
    exit 0
  fi
  echo "generate-cli-reference: docs/synapse-bard/cli.md is out of date -- run docs/synapse-bard/generate-cli-reference.sh" >&2
  diff <(render) "$OUT" | head -20 >&2
  exit 1
fi

render > "$OUT"
printf 'wrote %s (%s subcommands, %s lines)\n' \
  "$OUT" "$(subcommands | wc -l | tr -d ' ')" "$(wc -l < "$OUT" | tr -d ' ')"
